libgrading: Test Class Reference
Test Class Reference
A single, completely-initialized test.
#include <libgrading.h>
Public Types
typedef std::unordered_set< std::string > TagSet
A set of arbitrary tags that can be used when selecting tests.
Public Member Functions
Test (std::string name, std::string description, TestClosure, time_t timeout=0, unsigned int weight=1, TagSet tags=TagSet())
Standard constructor.
template<class Expectation >
Test (std::string name, std::string description, std::function< void(const Expectation &)> fn, Expectation e, time_t timeout=0, unsigned int weight=1)
Function-plus-expectation constructor.
template<class Expectation >
Test (std::string name, std::string description, void(*fn)(const Expectation &), Expectation e, time_t timeout=0, unsigned int weight=1)
Function-pointer constructor.
std::string name () const
User-meaningful test name (ideally a single line or less).
std::string description () const
A longer test description. May contain newlines.
time_t timeout () const
Maximum length of time this test should take (or 0 for unlimited).
unsigned int weight () const
How much weight to place on this test when calculating final score.
TestResult Run (TestRunStrategy strategy, time_t timeout=0) const
Run this test.
Friends
class TestBuilder
Detailed Description
A single, completely-initialized test.
Definition at line 171 of file libgrading.h.
Member Typedef Documentation
TagSet
typedef std::unordered_set<std::string> TagSet
A set of arbitrary tags that can be used when selecting tests.
Tag-informed test running isn't implemented yet, but we want to be able to select, e.g., only the short tests or only the bonus tests.
Definition at line 180 of file libgrading.h.
Constructor & Destructor Documentation
Test() [1/3]
Test (std::string name, std::string description, TestClosure test, time_t timeout = 0, unsigned int weight = 1, TagSet tags = TagSet())
Standard constructor.
Takes a TestClosure that represents the test we are actually going to run.
Definition at line 29 of file Test.cpp.
Test() [2/3]
Test (std::string name, std::string description, std::function< void(const Expectation &)> fn, Expectation e, time_t timeout = 0, unsigned int weight = 1) inline
Function-plus-expectation constructor.
Takes a single-argument std::function and a single value to pass into that function (e.g., a common-to-all-tests TestStudentFunction(const Expectation&) and an Expectation value that describes a particular test case).
Definition at line 201 of file libgrading.h.
Test() [3/3]
Test (std::string name, std::string description, void(*)(const Expectation &) fn, Expectation e, time_t timeout = 0, unsigned int weight = 1) inline
Function-pointer constructor.
Takes a pointer to a single-argument function and a single value to pass into that function (e.g., a common-to-all-tests TestStudentFunction(const Expectation&) and an Expectation value that describes a particular test case).
Definition at line 217 of file libgrading.h.
Member Function Documentation
description()
std::string description () const inline
A longer test description. May contain newlines.
Definition at line 228 of file libgrading.h.
name()
std::string name () const inline
User-meaningful test name (ideally a single line or less).
Definition at line 225 of file libgrading.h.
Run()
TestResult Run (TestRunStrategy strategy, time_t timeout = 0) const
Run this test.
Parameters
strategy how to run the test (e.g., sandboxed)
timeout how long to wait for completion (0 = forever)
Definition at line 37 of file Test.cpp.
References grading::EnterSandbox(), grading::ForkTest(), grading::Inline, grading::Pass, grading::Sandboxed, grading::Separated, and Test::timeout().
timeout()
time_t timeout () const inline
Maximum length of time this test should take (or 0 for unlimited).
Definition at line 231 of file libgrading.h.
Referenced by Test::Run().
weight()
unsigned int weight () const inline
How much weight to place on this test when calculating final score.
Definition at line 234 of file libgrading.h.
The documentation for this class was generated from the following files:
include/libgrading.h
src/Test.cpp