libgrading: grading::CheckResult Class Reference
grading::CheckResult Class Reference
The result of executing a CheckSomething() function.
#include <libgrading.h>
Public Member Functions
CheckResult ()
"All's-well" constructor (i.e., the check passed).
CheckResult (std::string message)
Constructor that takes a simple error message.
CheckResult (std::string exected, std::string actual)
Constructor that takes an expected and actual value.
CheckResult (const CheckResult &)=delete
CheckResult (CheckResult &&)
Move constructor. Steal error result from a temporary CheckResult.
CheckResult & operator<< (const std::vector< std::string > &)
Add further error details to this result, should it be a failure.
template<class T >
CheckResult & operator<< (const T &x)
Add further error details to this result, should it be a failure.
bool error () const
Whether or not the check result is erroneous.
void cancel ()
Cancel the error: the result is actually ok (e.g., because of a logical OR) or else the error's ownership is being transferred to another CheckResult.
std::string actual () const
Value test expected to see (user-readable representation).
std::string expected () const
Actual value that was seen (user-readable representation).
std::string message () const
A message to display if the check fails.
Detailed Description
The result of executing a CheckSomething() function.
Definition at line 256 of file libgrading.h.
Constructor & Destructor Documentation
grading::CheckResult::CheckResult ()
"All's-well" constructor (i.e., the check passed).
Definition at line 36 of file checks.cpp.
grading::CheckResult::CheckResult (std::string message)
Constructor that takes a simple error message.
Definition at line 41 of file checks.cpp.
grading::CheckResult::CheckResult (std::string exected, std::string actual)
Constructor that takes an expected and actual value.
Definition at line 46 of file checks.cpp.
grading::CheckResult::CheckResult (CheckResult && other)
Move constructor. Steal error result from a temporary CheckResult.
Definition at line 51 of file checks.cpp.
Member Function Documentation
std::string grading::CheckResult::actual () const inline
Value test expected to see (user-readable representation).
Definition at line 297 of file libgrading.h.
void grading::CheckResult::cancel () inline
Cancel the error: the result is actually ok (e.g., because of a logical OR) or else the error's ownership is being transferred to another CheckResult.
Definition at line 294 of file libgrading.h.
Referenced by grading::operator&&(), and grading::operator||().
bool grading::CheckResult::error () const inline
Whether or not the check result is erroneous.
Definition at line 287 of file libgrading.h.
std::string grading::CheckResult::expected () const inline
Actual value that was seen (user-readable representation).
Definition at line 300 of file libgrading.h.
std::string grading::CheckResult::message () const inline
A message to display if the check fails.
Definition at line 303 of file libgrading.h.
Referenced by grading::operator&&().
CheckResult & grading::CheckResult::operator<< (const std::vector< std::string > & v)
Add further error details to this result, should it be a failure.
Definition at line 135 of file checks.cpp.
template<class T > CheckResult& grading::CheckResult::operator<< (const T & x) inline
Add further error details to this result, should it be a failure.
Definition at line 280 of file libgrading.h.
The documentation for this class was generated from the following files:
include/libgrading.h
src/checks.cpp
src/posix.cpp