libgrading: TestSuite Class Reference
TestSuite Class Reference
A collection of tests that we can run.
#include <libgrading.h>
Classes
struct Statistics
Summary statistics about the execution of a TestSuite.
Public Member Functions
TestSuite ()
Default constructor: create an empty test suite.
TestSuite (std::initializer_list< Test >)
Construct a TestSuite from a brace-enclosed list of Test objects.
TestBuilder add (std::string name)
Start creating a test with a given name.
TestSuite & add (Test)
Add an already-complete Test to this suite.
unsigned int totalWeight () const
The total weight of all tests in the suite.
Statistics Run (int argc, char *argv[]) const
Run all tests, using command-line arguments to guide the testing strategy, timeouts, etc.
Detailed Description
A collection of tests that we can run.
Definition at line 87 of file libgrading.h.
Constructor & Destructor Documentation
TestSuite() [1/2]
TestSuite ()
Default constructor: create an empty test suite.
Definition at line 28 of file TestSuite.cpp.
TestSuite() [2/2]
TestSuite (std::initializer_list< Test > tests)
Construct a TestSuite from a brace-enclosed list of Test objects.
Definition at line 33 of file TestSuite.cpp.
Member Function Documentation
add() [1/2]
TestBuilder add (std::string name)
Start creating a test with a given name.
When the TestBuilder goes out of scope, it will add a complete Test to this suite.
Parameters
name user-meaningful test name
Precondition
name should not be empty
Definition at line 39 of file TestSuite.cpp.
add() [2/2]
TestSuite & add (Test test)
Add an already-complete Test to this suite.
Definition at line 47 of file TestSuite.cpp.
Run()
TestSuite::Statistics Run (int argc, char * argv[]) const
Run all tests, using command-line arguments to guide the testing strategy, timeouts, etc.
Returns
summary statistics about the suite run
Definition at line 67 of file TestSuite.cpp.
References Formatter::Create(), Arguments::error, TestSuite::Statistics::failed, Arguments::help, Arguments::outputFormat, Arguments::Parse(), grading::Pass, TestSuite::Statistics::passed, Arguments::runStrategy, TestSuite::Statistics::score, Arguments::skip, TestResult::status, Arguments::timeout, TestSuite::Statistics::total, and TestSuite::totalWeight().
totalWeight()
unsigned int totalWeight () const
The total weight of all tests in the suite.
Definition at line 54 of file TestSuite.cpp.
Referenced by TestSuite::Run().
The documentation for this class was generated from the following files:
include/libgrading.h
src/TestSuite.cpp