libgrading: grading Namespace Reference
grading Namespace Reference
Container for all libgrading names.
Classes
class CheckResult
The result of executing a CheckSomething() function.
class SharedMemory
A representation of a shared memory object.
class Test
A single, completely-initialized test.
class TestBuilder
An object used to construct a complete Test.
class TestSuite
A collection of tests that we can run.
Typedefs
typedef std::function< void()> TestClosure
A closure that wraps a single test case.
Enumerations
enum TestResult : char {
TestResult::Pass, TestResult::Fail, TestResult::Abort, TestResult::Segfault,
TestResult::Timeout, TestResult::UncaughtException, TestResult::OtherError
}
The result of running one test.
enum TestRunStrategy { TestRunStrategy::Inline, TestRunStrategy::Separated, TestRunStrategy::Sandboxed }
Ways that we can run tests.
Functions
CheckResult operator&& (CheckResult &&, CheckResult &&)
Combine the results of two checks using a product (AND): both must pass.
CheckResult operator&& (CheckResult &&, CheckResult &)
L-value version of above.
CheckResult operator|| (CheckResult &&, CheckResult &&)
Combine the results of two checks using a sum (OR): at least one must pass.
CheckResult operator|| (CheckResult &&, CheckResult &)
L-value version of above.
CheckResult Check (bool, std::string description)
Check an arbitrary condition, failing the test if false.
CheckResult CheckInt (int expected, int actual)
Check that two integers are equal, failing the test if they are not.
CheckResult CheckFloat (double exp, double act, double tolerance=0.000001)
Check that two floating-point numbers are equal within some tolerance.
CheckResult CheckNonNull (const void *, std::string message)
Check that a pointer is not equal to nullptr.
CheckResult CheckNull (const void *, std::string message)
Check that a pointer is equal to nullptr.
CheckResult CheckString (std::string expected, std::string actual, size_t maxEditDistance=0)
Check that two strings are (approximately) equal.
CheckResult Fail (std::string message)
Fail the current test.
std::ostream & operator<< (std::ostream &, TestResult)
Output a human-readable representation of a TestResult.
std::unique_ptr< SharedMemory > MapSharedData (size_t size)
Map data into the address space that can be shared with other processes.
TestResult RunTest (TestClosure test, std::string name="<unnamed test>", time_t timeout=0, std::ostream &errorStream=std::cerr)
Run a test closure in a separate process, capturing segmentation faults and other errors that lead to termination.
template<class T >
TestResult RunTest (std::function< TestResult(T &)> test, T &output, std::string name="<unnamed test>", time_t timeout=0, std::ostream &errorStream=std::cerr)
Run a test with output but no explicit input.
template<class Expectation , class Output >
TestResult RunTest (std::function< TestResult(const Expectation &, Output &)> t, const Expectation &expect, Output &output, std::string name="<unnamed test>", time_t timeout=0, std::ostream &errorStream=std::cerr)
Run a test with input and output.
void EnterSandbox ()
TestResult ForkTest (TestClosure test, time_t timeout, std::ostream &errStream)
TestResult RunInProcess (TestClosure test)
Detailed Description
Container for all libgrading names.
Typedef Documentation
typedef std::function<void ()> grading::TestClosure
A closure that wraps a single test case.
Definition at line 118 of file libgrading.h.
Enumeration Type Documentation
enum grading::TestResult : char strong
The result of running one test.
Enumerator
Pass
the test succeeded
Fail
the test failed
Abort
the test was aborted (e.g., assert() fired)
Segfault
the test caused a segmentation fault
Timeout
the test took too long to run
UncaughtException
the test threw an exception
OtherError
the test terminated for another reason
Definition at line 44 of file libgrading.h.
enum grading::TestRunStrategy strong
Ways that we can run tests.
We can select among these at run-time with the command-line argument --strategy=inline|separated|sandboxed.
Enumerator
Inline
In the same process, in the current call stack.
Separated
In separate but unsandboxed processes.
Sandboxed
In a separate, sandboxed process (if supported).
Definition at line 62 of file libgrading.h.
Function Documentation
CheckResult grading::Check (bool condition, std::string description)
Check an arbitrary condition, failing the test if false.
Definition at line 156 of file checks.cpp.
CheckResult grading::CheckFloat (double exp, double act, double tolerance = 0.000001)
Check that two floating-point numbers are equal within some tolerance.
Definition at line 188 of file checks.cpp.
CheckResult grading::CheckInt (int expected, int actual)
Check that two integers are equal, failing the test if they are not.
Definition at line 164 of file checks.cpp.
CheckResult grading::CheckNonNull (const void * ptr, std::string message)
Check that a pointer is not equal to nullptr.
Definition at line 172 of file checks.cpp.
CheckResult grading::CheckNull (const void * ptr, std::string message)
Check that a pointer is equal to nullptr.
Definition at line 180 of file checks.cpp.
CheckResult grading::CheckString (std::string expected, std::string actual, size_t maxEditDistance = 0)
Check that two strings are (approximately) equal.
Parameters
expected the string we expected
actual the string we got
maxEditDistance how fuzzy the match can be: the maximum Levenshtein distance between them
Definition at line 203 of file checks.cpp.
CheckResult grading::Fail (std::string message)
Fail the current test.
Definition at line 218 of file checks.cpp.
Referenced by operator<<().
unique_ptr< SharedMemory > grading::MapSharedData (size_t size)
Map data into the address space that can be shared with other processes.
Definition at line 117 of file posix.cpp.
Referenced by RunTest().
CheckResult grading::operator&& (CheckResult && x, CheckResult && y)
Combine the results of two checks using a product (AND): both must pass.
Definition at line 66 of file checks.cpp.
CheckResult grading::operator&& (CheckResult && x, CheckResult & y)
L-value version of above.
Definition at line 99 of file checks.cpp.
std::ostream & grading::operator<< (std::ostream & out, TestResult result)
Output a human-readable representation of a TestResult.
Definition at line 26 of file TestResult.cpp.
References Fail().
CheckResult grading::operator|| (CheckResult && x, CheckResult && y)
Combine the results of two checks using a sum (OR): at least one must pass.
Definition at line 105 of file checks.cpp.
CheckResult grading::operator|| (CheckResult && x, CheckResult & y)
L-value version of above.
Definition at line 129 of file checks.cpp.
TestResult grading::RunTest (TestClosure test, std::string name = "<unnamed test>", time_t timeout = 0, std::ostream & errorStream = std::cerr)
Run a test closure in a separate process, capturing segmentation faults and other errors that lead to termination.
Parameters
test the test to run
name a developer-friendly name
timeout the number of seconds to let the test run (default 0, meaning "no timeout, run forever")
errorStream where to write messages (e.g., "expected X, got Y")
Returns
the result of the test, either pass/fail as reported by test or else segfault/other as captured by libgrading
Referenced by RunTest().
template<class T > TestResult grading::RunTest (std::function< TestResult(T &)> test, T & output, std::string name = "<unnamed test>", time_t timeout = 0, std::ostream & errorStream = std::cerr)
Run a test with output but no explicit input.
Parameters
test a test function that copies out an output value and returns a TestResult
output the output value produced by test (if it executes normally, e.g., without segfaulting)
name a developer-friendly name
timeout the number of seconds to let the test run (default 0, meaning "no timeout, run forever")
errorStream where to write messages (e.g., "expected X, got Y")
Returns
the result of the test, either pass/fail as reported by test or else segfault/other as captured by libgrading
Definition at line 399 of file libgrading.h.
References MapSharedData(), grading::SharedMemory::rawPointer(), and RunTest().
template<class Expectation , class Output > TestResult grading::RunTest (std::function< TestResult(const Expectation &, Output &)> t, const Expectation & expect, Output & output, std::string name = "<unnamed test>", time_t timeout = 0, std::ostream & errorStream = std::cerr)
Run a test with input and output.
Parameters
t a test function that takes an input expectation, copies out an output value and returns a TestResult
expect our test expectation (inputs, expected output, etc.)
output the output value produced by test (if it executes normally, e.g., without segfaulting)
name a developer-friendly name
timeout the number of seconds to let the test run (default 0, meaning "no timeout, run forever")
errorStream where to write messages (e.g., "expected X, got Y")
Returns
the result of the test, either pass/fail as reported by test or else segfault/other as captured by libgrading
Definition at line 433 of file libgrading.h.