libgrading: Arguments Struct Reference
Arguments Struct Reference
Parsed command-line arguments.
#include <private.h>
Public Member Functions
Arguments (bool help=false)
Construct a "failed to parse normal arguments" object.
Arguments (bool error, bool help, OutputFormat, bool skip, TestRunStrategy, time_t timeout)
Normal Arguments constructor.
Static Public Member Functions
static Arguments Parse (int argc, char *argv[])
Parse command-line arguments.
Public Attributes
const bool error
There was an error parsing command-line arguments.
const bool help
The --help argument was given.
const OutputFormat outputFormat
How to format test outputs.
const bool skip
The --skip argument was given.
const TestRunStrategy runStrategy
The TestRunStrategy chosen by the user (e.g., inline).
const time_t timeout
Maximum length of time to wait for any test.
Detailed Description
Parsed command-line arguments.
Definition at line 42 of file private.h.
Constructor & Destructor Documentation
Arguments() [1/2]
Arguments (bool help = false)
Construct a "failed to parse normal arguments" object.
Definition at line 189 of file Arguments.cpp.
References grading::Inline, and grading::Verbose.
Referenced by Arguments::Parse().
Arguments() [2/2]
Arguments (bool error, bool help, OutputFormat format, bool skip, TestRunStrategy strategy, time_t timeout)
Normal Arguments constructor.
Definition at line 196 of file Arguments.cpp.
Member Function Documentation
Parse()
Arguments Parse (int argc, char * argv[]) static
Parse command-line arguments.
Definition at line 98 of file Arguments.cpp.
References Arguments::Arguments(), and usage.
Referenced by TestSuite::Run().
Member Data Documentation
error
const bool error
There was an error parsing command-line arguments.
Definition at line 55 of file private.h.
Referenced by TestSuite::Run().
help
const bool help
The --help argument was given.
Definition at line 58 of file private.h.
Referenced by TestSuite::Run().
outputFormat
const OutputFormat outputFormat
How to format test outputs.
Definition at line 61 of file private.h.
Referenced by TestSuite::Run().
runStrategy
const TestRunStrategy runStrategy
The TestRunStrategy chosen by the user (e.g., inline).
Definition at line 67 of file private.h.
Referenced by TestSuite::Run().
skip
const bool skip
The --skip argument was given.
Definition at line 64 of file private.h.
Referenced by TestSuite::Run().
timeout
const time_t timeout
Maximum length of time to wait for any test.
Definition at line 70 of file private.h.
Referenced by TestSuite::Run().
The documentation for this struct was generated from the following files:
src/private.h
src/Arguments.cpp